spring:
  application:
    name: msvc-coupon
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST:localhost:27017}/${MSVC_COUPON_DB:msvc-coupon}
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/