spring:
  application:
    name: msvc-products
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST:localhost:27017}/${MSVC_PRODUCTS_DB:msvc-products}
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/