spring:
  application:
    name: msvc-products
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/msvc-products
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8080