spring:
  application:
    name: msvc-enquire
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST:localhost:27017}/${MSVC_ENQUIRE_DB:msvc-enquire}
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/