spring:
  application:
    name: msvc-cart
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost:3306}/${MSVC_CART_DB:msvc-cart}?serverTimezone=America/Lima
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/