spring:
  application:
    name: msvc-users
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres15:5432}/${DB_DATABASE:msvc-users}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8088