spring:
  application:
    name: msvc-users
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost:5532}/${MSVC_USERS_DB:msvc-users}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASS:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/